# Generated by Django 2.1.5 on 2020-05-28 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='In_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'In_order',
            },
        ),
        migrations.CreateModel(
            name='Menu_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(null=True, verbose_name='Price per item')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Placed_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Placed_Orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='menu_item',
            name='pizza_style',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.Pizza_Style'),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='size',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.Size'),
        ),
        migrations.AddField(
            model_name='in_order',
            name='menu_item',
            field=models.ManyToManyField(related_name='In_Order', to='orders.Menu_Item'),
        ),
        migrations.AddField(
            model_name='in_order',
            name='placed_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='In_Order', to='orders.Placed_Order'),
        ),
    ]
