# Generated by Django 2.1.5 on 2020-05-28 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='pizza_style',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.Pizza_Style'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='size',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.Size'),
        ),
    ]
