# Generated by Django 2.1.5 on 2020-05-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200528_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_heading',
            field=models.BooleanField(default=True),
        ),
    ]
